<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>

# Backpropagation Practice

## *Data Science Unit 4 Sprint 2 Assignment 2*

Implement a 3 input, 4 node hidden-layer, 1 output node Multilayer Perceptron on the following dataset:

| x1 | x2 | x3 | y |
|----|----|----|---|
| 0  | 0  | 1  | 0 |
| 0  | 1  | 1  | 1 |
| 1  | 0  | 1  | 1 |
| 0  | 1  | 0  | 1 |
| 1  | 0  | 0  | 1 |
| 1  | 1  | 1  | 0 |
| 0  | 0  | 0  | 0 |

If you look at the data you'll notice that the first two columns behave like an XOR gate while the last column is mostly just noise. Remember that creating an XOR gate was what the perceptron was criticized for not being able to learn. 

In [32]:
import numpy as np

X = np.array([
    [0,0,1,0,1,1,0],
    [0,1,0,1,0,1,0],
    [1,1,1,0,0,1,0]
])

X

array([[0, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0, 1, 0]])

In [43]:
y = np.array([
    [0],
])

In [44]:
#don't need to, everything is 0 or 1 already
#normalizing
#X = X / np.amax(X, axis=0)
#y = y / 100

#print("Input \n", X)
#print("Output \n", y)

In [45]:
class NeuralNetwork: 
    
    def __init__(self):
        # Setup Arch
        self.inputs = 3
        self.hiddenNodes = 4 
        self.outputNodes = 1
        
        # Initialize Weights
        # 3x7
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
        
        # 7x1
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)

In [46]:
nn = NeuralNetwork()

print("Layer 1 weights: \n", nn.weights1)
print("Layer 2 weights: \n", nn.weights2)

Layer 1 weights: 
 [[ 1.14725181  0.83963441 -0.33508809  2.17590867]
 [-0.84239946 -0.22032384  0.28503704 -0.45540355]
 [ 0.81830927  0.55467968  1.39494163  1.41120076]]
Layer 2 weights: 
 [[ 1.06122129]
 [-0.54439254]
 [-0.02207013]
 [-2.05256516]]


In [47]:
class NeuralNetwork: 
    
    def __init__(self):
        # Setup Arch
        self.inputs = 3
        self.hiddenNodes = 4 
        self.outputNodes = 1
        
        # Initialize Weights
        # 3x7
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
        
        # 7x1
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        """
        
        # Weight Sum
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activation
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weighted Sum 2
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final Output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output

In [48]:
X

array([[0, 0, 1, 0, 1, 1, 0],
       [0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 0, 0, 1, 0]])

In [49]:
nn = NeuralNetwork()
output = nn.feed_forward(X[0])
print("intput", X[0])
print("output", output)
print("true_output", y[0])

ValueError: shapes (7,) and (3,4) not aligned: 7 (dim 0) != 3 (dim 0)

In [13]:
error = y[0] - output
print(error)

[-0.78482389  0.21517611  0.21517611  0.21517611  0.21517611 -0.78482389
 -0.78482389]


In [14]:
output_all = nn.feed_forward(X)
error_all = y - output_all
print(output_all)
print(error_all)
print(y)

[[0.78482389]
 [0.69161598]
 [0.66644625]]
[[-0.78482389  0.21517611  0.21517611  0.21517611  0.21517611 -0.78482389
  -0.78482389]
 [-0.69161598  0.30838402  0.30838402  0.30838402  0.30838402 -0.69161598
  -0.69161598]
 [-0.66644625  0.33355375  0.33355375  0.33355375  0.33355375 -0.66644625
  -0.66644625]]
[[0 1 1 1 1 0 0]]


In [15]:
#lets see if we can figure out what needs to be updated
attributes = ['weights1', 'hidden_sum', 'activated_hidden', 'weights2', 'activated_output']
[print(i+'\n', getattr(nn,i), '\n'+'---'*3) for i in attributes if i[:7]!= '__'] 

weights1
 [[-0.41094445 -1.26684221 -1.27997461]
 [-0.15251957 -0.18019745 -0.40284008]
 [ 1.71747131  0.23500273 -0.59337072]
 [ 1.40051286 -1.31713677 -1.21022628]
 [ 0.09947906 -1.05669442  1.32145053]
 [-1.41735904 -1.35896798  1.30412841]
 [ 0.38637223  0.79634107 -1.12276249]] 
---------
hidden_sum
 [[ 0.39959133 -2.18065967  2.03220822]
 [-0.16936576 -2.8563022  -0.30893795]
 [-0.26335176 -2.57100491 -0.972057  ]] 
---------
activated_hidden
 [[0.59858947 0.10150075 0.88413748]
 [0.45775948 0.05435646 0.42337399]
 [0.43453995 0.07102797 0.27447069]] 
---------
weights2
 [[1.08040939]
 [0.54995568]
 [0.66896827]] 
---------
activated_output
 [[0.78482389]
 [0.69161598]
 [0.66644625]] 
---------


[None, None, None, None, None]

In [22]:
# I want activations that correspond to negative weights to be lower
# and activations that correspond to positive weights to be higher
import numpy as np

class NeuralNetwork: 
    
    def __init__(self):
        # Setup Arch
        self.inputs = 3
        self.hiddenNodes = 3 
        self.outputNodes = 1
        
        # Initialize Weights
        #3x7
        self.weights1 = np.random.randn(self.inputs, self.hiddenNodes)
        
        # 7x1
        self.weights2 = np.random.randn(self.hiddenNodes, self.outputNodes)
        
    def sigmoid(self, s):
        return 1 / (1+np.exp(-s))
    
    def sigmoidPrime(self, s):
        sx = self.sigmoid(s)
        return sx * (1-sx)
    
    def feed_forward(self, X):
        """
        Calculate the NN inference using feed forward.
        """
        
        # Weight Sum
        self.hidden_sum = np.dot(X, self.weights1)
        
        # Activation
        self.activated_hidden = self.sigmoid(self.hidden_sum)
        
        # Weighted Sum 2
        self.output_sum = np.dot(self.activated_hidden, self.weights2)
        
        # Final Output
        self.activated_output = self.sigmoid(self.output_sum)
        
        return self.activated_output
    
    def backward(self, X,y,o):
        """
        Back prop thru the network
        """
        
        self.o_error = y - o
        
        # Apply derivative of sigmoid to error
        self.o_delta = self.o_error * self.sigmoidPrime(self.output_sum)
        
        # z2 error: how much were our output layer weights off
        self.z2_error = self.o_delta.dot(self.weights2.T)
        
        # z2 delta: how much were the weights off?
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.hidden_sum)

        self.weights1 += X.T.dot(self.z2_delta) #Adjust first set (input => hidden) weights
        self.weights2 += self.activated_hidden.T.dot(self.o_delta) #adjust second set (hidden => output) weights
        
    def train(self, X, y):
        o = self.feed_forward(X)
        self.backward(X,y,o)

In [23]:
#from reference import NeuralNetwork

nn = NeuralNetwork()

nn.train(X,y)

ValueError: shapes (3,7) and (3,3) not aligned: 7 (dim 1) != 3 (dim 0)

## Try building/training a more complex MLP on a bigger dataset.

Use the [MNIST dataset](http://yann.lecun.com/exdb/mnist/) to build the cannonical handwriting digit recognizer and see what kind of accuracy you can achieve. 

If you need inspiration, the internet is chalk-full of tutorials, but I want you to see how far you can get on your own first. I've linked to the original MNIST dataset above but it will probably be easier to download data through a neural network library. If you reference outside resources make sure you understand every line of code that you're using from other sources, and share with your fellow students helpful resources that you find.


In [ ]:
##### Your Code Here #####

## Stretch Goals: 

- Implement Cross Validation model evaluation on your MNIST implementation 
- Research different [Gradient Descent Based Optimizers](https://keras.io/optimizers/)
 - [Siraj Raval the evolution of gradient descent](https://www.youtube.com/watch?v=nhqo0u1a6fw)
- Build a housing price estimation model using a neural network. How does its accuracy compare with the regression models that we fit earlier on in class?